"""
sim_tool.launcher_log
─────────────────────
Append-only markdown log for the Launcher.

Two concerns, one file
───────────────────────
1. SESSION LOG — every launch attempt is recorded with:
   timestamp, session, script, outcome, env, pattern matched, fix applied.
   Machine-readable (each entry has a consistent header).

2. FAQ — patterns seen ≥2 times are automatically promoted to a FAQ section
   at the top of the file. This makes the most common problems immediately
   visible without scrolling through history.

File location:  ~/.sim_tool/launcher_log.md  (default)
Format:         Markdown — human-readable and hand-editable.
                The FAQ section is regenerated from scratch on each write.

Usage
─────
  from sim_tool.launcher_log import LauncherLog

  log = LauncherLog()

  # Record a successful launch
  log.record_success(session_id, script_path, env_info, wall_time)

  # Record a failed launch
  log.record_failure(session_id, script_path, ticket)

  # Show the full log
  print(log.show())

  # Get FAQ entries (patterns seen ≥2 times)
  faq = log.get_faq()
"""

from __future__ import annotations

import json
import logging
import re
from collections import Counter
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

log = logging.getLogger("sim_tool.launcher_log")

_DEFAULT_LOG_DIR = Path.home() / ".sim_tool"
_FAQ_MIN_OCCURRENCES = 2


@dataclass
class LogEntry:
    """Parsed representation of one launcher log entry."""
    timestamp:   str
    session_id:  str
    script_name: str
    outcome:     str          # "success" | "bug_ticket"
    kind:        str          # BugKind.value or "ok"
    pattern:     str          # which failure pattern matched, or ""
    fix:         str          # suggested_fix, or ""
    wall_time:   float
    metadata:    dict


class LauncherLog:
    """
    Append-only launcher event log with automatic FAQ generation.

    Parameters
    ----------
    log_dir : Override the default ~/.sim_tool directory.
    """

    def __init__(self, log_dir: Optional[Path] = None) -> None:
        self._dir = Path(log_dir) if log_dir else _DEFAULT_LOG_DIR
        self._dir.mkdir(parents=True, exist_ok=True)
        self._path = self._dir / "launcher_log.md"

        if not self._path.exists():
            self._path.write_text(
                "# Launcher Log\n\n"
                "Auto-generated by sim_tool. Human-editable.\n"
                "FAQ entries are regenerated from session history automatically.\n\n"
                "---\n\n"
            )
            log.debug(f"Created launcher log: {self._path}")
        else:
            n = self._count_entries()
            log.debug(f"Loaded launcher log: {n} entries from {self._path}")

    # ── Public write API ──────────────────────────────────────────────────────

    def record_success(
        self,
        session_id: str,
        script_path: str,
        env_summary: str,
        wall_time: float,
        configs_run: int = 0,
    ) -> None:
        """Record a successful launch."""
        entry = self._format_entry(
            session_id=session_id,
            script_name=Path(script_path).name,
            outcome="✓ success",
            kind="ok",
            wall_time=wall_time,
            body_lines=[
                f"  env      : {env_summary}",
                f"  configs  : {configs_run}",
            ],
            metadata={"outcome": "success", "kind": "ok", "pattern": ""},
        )
        self._append(entry)

    def record_failure(
        self,
        session_id: str,
        script_path: str,
        ticket,   # BugTicket — avoid circular import by not typing it
    ) -> None:
        """Record a failed launch with its bug ticket."""
        body_lines = [
            f"  exit     : {ticket.exit_code}",
            f"  pattern  : {ticket.failure_pattern or '(none matched)'}",
            f"  fix      : {ticket.suggested_fix}",
            f"  retryable: {ticket.is_retryable}",
        ]
        if ticket.error_line:
            body_lines.append(f"  error    : {ticket.error_line[:120]}")
        if ticket.pipeline_script_path:
            body_lines.append(f"  pipeline : {ticket.pipeline_script_path}")

        entry = self._format_entry(
            session_id=session_id,
            script_name=Path(script_path).name,
            outcome=f"✗ {ticket.kind.value}",
            kind=ticket.kind.value,
            wall_time=ticket.wall_time_seconds,
            body_lines=body_lines,
            metadata={
                "outcome": "failure",
                "kind": ticket.kind.value,
                "pattern": ticket.failure_pattern,
                "fix": ticket.suggested_fix,
            },
        )
        self._append(entry)
        self._maybe_update_faq()

    # ── Public read API ───────────────────────────────────────────────────────

    def show(self) -> str:
        return self._path.read_text(encoding="utf-8")

    def get_faq(self) -> list[dict]:
        """
        Return FAQ entries: patterns seen ≥ FAQ_MIN_OCCURRENCES times.
        Each entry: {"pattern": str, "kind": str, "fix": str, "count": int}
        """
        entries = self._parse_entries()
        pattern_counter: Counter = Counter()
        pattern_to_fix: dict[str, str] = {}
        pattern_to_kind: dict[str, str] = {}

        for e in entries:
            p = e.pattern
            if p:
                pattern_counter[p] += 1
                if p not in pattern_to_fix and e.fix:
                    pattern_to_fix[p] = e.fix
                if p not in pattern_to_kind and e.kind:
                    pattern_to_kind[p] = e.kind

        return [
            {
                "pattern": pattern,
                "kind": pattern_to_kind.get(pattern, ""),
                "fix": pattern_to_fix.get(pattern, ""),
                "count": count,
            }
            for pattern, count in pattern_counter.most_common()
            if count >= _FAQ_MIN_OCCURRENCES
        ]

    @property
    def path(self) -> Path:
        return self._path

    @property
    def entry_count(self) -> int:
        return self._count_entries()

    # ── Internal ──────────────────────────────────────────────────────────────

    def _format_entry(
        self,
        session_id: str,
        script_name: str,
        outcome: str,
        kind: str,
        wall_time: float,
        body_lines: list[str],
        metadata: dict,
    ) -> str:
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_json = json.dumps(metadata)
        lines = [
            f"\n## [{ts}] {outcome} — `{script_name}`",
            f"<!-- meta: {meta_json} -->",
            f"  session  : {session_id}",
            f"  wall time: {wall_time:.1f}s",
        ] + body_lines
        return "\n".join(lines) + "\n"

    def _append(self, entry: str) -> None:
        with open(self._path, "a", encoding="utf-8") as f:
            f.write(entry)

    def _count_entries(self) -> int:
        content = self._path.read_text(encoding="utf-8")
        return content.count("\n## [")

    def _parse_entries(self) -> list[LogEntry]:
        """Parse all entries from the log file."""
        content = self._path.read_text(encoding="utf-8")
        entries: list[LogEntry] = []

        for block in re.split(r"\n## \[", content)[1:]:
            lines = block.strip().splitlines()
            if not lines:
                continue

            # Header: "2024-01-15 14:32:01] ✓ success — `sim.py`"
            header = lines[0]
            ts_match = re.match(r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] (.+?) — `(.+?)`", header)
            if not ts_match:
                continue
            ts, outcome, script = ts_match.groups()

            # Metadata from HTML comment
            meta: dict = {}
            for line in lines[1:5]:
                m = re.search(r"<!-- meta: (.+?) -->", line)
                if m:
                    try:
                        meta = json.loads(m.group(1))
                    except json.JSONDecodeError:
                        pass

            # Extract wall time
            wall_time = 0.0
            for line in lines:
                m = re.search(r"wall time: ([\d.]+)s", line)
                if m:
                    wall_time = float(m.group(1))

            entries.append(LogEntry(
                timestamp=ts,
                session_id=meta.get("session_id", ""),
                script_name=script,
                outcome=outcome,
                kind=meta.get("kind", ""),
                pattern=meta.get("pattern", ""),
                fix=meta.get("fix", ""),
                wall_time=wall_time,
                metadata=meta,
            ))

        return entries

    def _maybe_update_faq(self) -> None:
        """Regenerate the FAQ section if there are patterns worth surfacing."""
        faq = self.get_faq()
        if not faq:
            return

        content = self._path.read_text(encoding="utf-8")

        # Remove old FAQ section if present
        faq_marker = "\n## FAQ — Frequently Seen Failures\n"
        faq_end_marker = "\n---\n\n"
        if faq_marker in content:
            faq_start = content.index(faq_marker)
            after_faq = content.find(faq_end_marker, faq_start)
            if after_faq != -1:
                content = content[:faq_start] + content[after_faq:]
            else:
                content = content[:faq_start]

        # Build new FAQ section
        faq_lines = [faq_marker.rstrip()]
        faq_lines.append(
            f"_Auto-generated from {self.entry_count} session(s). "
            f"Patterns seen ≥{_FAQ_MIN_OCCURRENCES} times._\n"
        )
        for item in faq:
            faq_lines.append(f"### `{item['pattern']}` ({item['count']}×, kind: {item['kind']})")
            faq_lines.append(f"**Fix:** {item['fix']}\n")

        # Insert FAQ after file header (before first entry)
        first_entry = content.find("\n## [")
        if first_entry == -1:
            content += "\n".join(faq_lines) + faq_end_marker
        else:
            content = (
                content[:first_entry]
                + "\n".join(faq_lines)
                + faq_end_marker
                + content[first_entry:]
            )

        self._path.write_text(content, encoding="utf-8")
        log.debug(f"FAQ updated: {len(faq)} pattern(s)")
