"""
coding.plan_functions
─────────────────────
Tool: Analyse a research goal and decide what functions the simulation
needs, returning a list of function specs with signatures and docstrings.
"""
from __future__ import annotations

from typing import Any

from ...contracts import AssistantId
from ...registry import ArtifactRegistry
from ..base import ToolContext, ToolDescriptor, ToolRequirement, ToolResult
from ..validators import artifact_kind_is, is_non_empty_string

TOOL = ToolDescriptor(
    name="plan_simulation_functions",
    display_name="Plan Simulation Functions",
    description=(
        "Analyse a research goal, article brief, and literature context to "
        "decide what functions the simulation needs.  Returns a plan listing "
        "function specs — each with name, signature, docstring, and context — "
        "that can be individually generated by generate_function."
    ),
    agent_id="coding",
    requirements=[
        ToolRequirement(
            name="instruction",
            description="The PI's research directive text",
            type="str",
            validator=is_non_empty_string,
            validator_description="Must be a non-empty instruction string",
        ),
        ToolRequirement(
            name="brief",
            description="The article brief ArtifactRef with model description and parameters",
            type="ArtifactRef",
            validator=artifact_kind_is("article_brief"),
            validator_description="Must be an 'article_brief' artifact",
        ),
        ToolRequirement(
            name="literature",
            description="The literature review ArtifactRef with synthesis context",
            type="ArtifactRef",
            required=False,
        ),
    ],
    produces=["simulation_plan"],
    tags=["coding", "planning", "design"],
    idempotent=True,
    estimated_seconds=20.0,
)


def execute(
    context: ToolContext,
    *,
    registry: ArtifactRegistry,
    llm_config: Any = None,
) -> ToolResult:
    """Use the designer LLM to plan the functions needed for the simulation."""
    from ...assistants.backends import make_service_backend

    brief = context.artifacts["brief"]
    literature = context.artifacts.get("literature")
    instruction = context.inputs.get("instruction", context.instruction)

    # Build research goal text from artifacts
    params = brief.metadata.get("key_parameters") or {}
    figures = brief.metadata.get("expected_figures") or []
    inquiries = brief.metadata.get("inquiries") or []
    inquiry_answers = context.metadata.get("inquiry_answers") or {}
    lit_summary = ""
    if literature:
        lit_summary = str(literature.metadata.get("synthesis") or literature.summary or "")

    research_goal = (
        f"{instruction}\n\n"
        f"Model description:\n{brief.metadata.get('model_description', '')}\n\n"
        f"Procedure:\n{brief.metadata.get('procedure', '')}\n\n"
        f"Key parameters:\n{_safe_json(params)}\n\n"
        f"Expected figures:\n" + "\n".join(f"- {f}" for f in figures) + "\n\n"
        f"Open inquiries:\n{_safe_json(inquiries)}\n\n"
        f"Resolved inquiry answers:\n{_safe_json(inquiry_answers)}\n\n"
        f"Related literature context:\n{lit_summary}"
    )

    backend = make_service_backend("designer", llm_config) if llm_config else None
    if backend is None:
        return ToolResult(status="failed", message="No LLM backend available for function planning")

    try:
        import json
        raw = backend.complete(
            system=(
                "You are a simulation architect.  Given a research goal, plan the Python functions "
                "needed to implement the simulation.  Return ONLY a JSON array of objects, each with:\n"
                '  {"name": "...", "signature": "...", "docstring": "...", "context": "...", "dependencies": [...]}\n'
                "Include setup, step, stopping, and analysis functions as needed."
            ),
            messages=[{"role": "user", "content": research_goal}],
            temperature=0.0,
        )
        plan = json.loads(raw) if isinstance(raw, str) else raw
    except Exception as exc:
        return ToolResult(status="failed", message=f"Function planning failed: {exc}")

    plan_ref = registry.save_json(
        assistant=AssistantId.CODING_AGENT.value,
        kind="simulation_plan",
        title="Simulation Function Plan",
        filename="simulation/function_plan.json",
        payload={"functions": plan, "research_goal": research_goal},
        summary=f"{len(plan)} function(s) planned",
        metadata={"function_count": len(plan)},
        artifact_id="simulation-function-plan",
    )
    follow_up_steps = []
    planned_names = []
    for item in plan:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name") or "function").strip()
        planned_names.append(name)
        follow_up_steps.append({
            "tool": "generate_function",
            "inputs": {"function_spec": item},
            "label": f"Generate simulation function: {name}",
        })
    return ToolResult(
        status="completed",
        artifacts=[plan_ref],
        message=f"Planned {len(planned_names)} function(s): {', '.join(planned_names)}",
        metadata={"plan": plan},
        follow_up_steps=follow_up_steps,
    )


def _safe_json(obj: Any) -> str:
    import json
    try:
        return json.dumps(obj, indent=2)
    except (TypeError, ValueError):
        return str(obj)
